# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170401_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
